### ISSUE TITLE
Illegal instruction when starting the python script

### ISSUE THREAD

**Issue by gitmanbloggus** [yukiarimo/yuna-ai#107]
**Describe the bug**
Got a "Illegal instuction (core dumped)" when starting the python script

**To Reproduce**
1. install as normal
2. try starting yuna

**Expected behavior**
ment to start up and begin loading the model

**Desktop (please complete the following information):**
 - OS: Endeavor os ARM (raspberry pi 4b 8gb ram)

**Additional context**
might be a bug in one of the pip packages

**Comment by yukiarimo** [comment]
Please reinstall `llama-cpp-python` using one of the following commands here: https://llama-cpp-python.readthedocs.io/en/latest/

**Comment by gitmanbloggus** [comment]
got it

**Comment by yukiarimo** [comment]
Please let me know if it will help!

**Comment by gitmanbloggus** [comment]
didnt work for some reason, it installed but 2 pip packages expected a older pip version, but still a core dumped error

**Comment by yukiarimo** [comment]
Something has been wrong with Python lately. Try reinstalling it. I can also catch this error sometimes. Closing for now as a typical Python bug; feel free to reopen!
