### ISSUE TITLE
Can't get yuna to respond

### ISSUE THREAD

**Issue by greentree-ai** [yukiarimo/yuna-ai#113]
I am running yuna from a docker container (python:3:12) and I cannot get yuna to say anything. I downloaded the model yuna-ai-v3-atomic-q_6_k.gguf and placed it in lib/models/yuna and updated the static/config.json  "yuna_default_model": "yuna-ai-v3-atomic-q_6_k"
Whenever I send a message, this is what the console says
```
Response content:
Response:
```
No errors.
My exact procedure is:
1) Start docker container
2) git clone
3) pip install -r requirements.txt
4) copy model to lib/models/yuna
5) configure config.json (or don't, I've tried both)
6) python index.py
7) send any message in chat

I feel like I'm missing something so this could be my fault.

**Comment by yukiarimo** [comment]
1. It’s not my problem, it’s llama-cpp-python
2. It’s V4 problem, so wait a little, or team currently is optimizing the model’s parameters 
3. Try KoboldCPP as a backend. Installation package and guide will be provided soon

**Comment by greentree-ai** [comment]
Ok, good to know I wasn't doing anything wrong. I'll look forward to Kobold guide

**Comment by yukiarimo** [comment]
I would also try implementing the MLX soon; hopefully, the don’t have this problem (spoiler: they do)

**Comment by yukiarimo** [comment]
Works well

**Comment by OndraTakacs** [comment]
> Ok, good to know I wasn't doing anything wrong. I'll look forward to Kobold guide

I got it working with Kobold! I can share my steps with you:

1. Download and run KoboldCpp
2. Set the path for the model yuna-ai-v3-atomic-q_6_k and run it
3. It should start Kobold interface in browser. The model should be responding. (It takes some time, you can see processing progress in console)
4. Run `python index.py` from Yuna project and Yuna should be responding!

This works for me. Let me know if you need help :-)
