### ISSUE TITLE
How to reproduce example about Elon Mask?

### ISSUE THREAD

**Issue by aksonov** [yukiarimo/yuna-ai#119]
The v3 model looks very stupid (q6_k), what model I should use?

<img width="1189" alt="Снимок экрана 2024-11-23 в 10 32 23" src="https://github.com/user-attachments/assets/909a3c60-3fae-4318-9f0e-639e7024dde9">

Also it is very very brief and stupid in usual conversations...

**Comment by yukiarimo** [comment]
1. Please wait for the next update. We are still working on the Kanojo Management!
2. V4 has not been released, but the current implementation has been made for V4.
3. Everything will be fixed this weekend. We are also working on the AiFlow.

I'll let you know when everything will be good. Please stay updated!

**Comment by yukiarimo** [comment]
Closing the issue

1. V4 won't be released
2. Wait for the V3.5 (latest version)
3. Update the YUI to work with new models
4. Or wait until Christmas/New year for a huge surprize :)
