### ISSUE TITLE
Finall Steps

### ISSUE THREAD

**Issue by cloner174** [yukiarimo/yuna-ai#17]
Hi,
I have this error on the very last step to finally could run Yuna:
                       ------------------------------
Error Key-Line :: 

{ ' PyTorch is not linked with support for mps devices ' }

---------------------------------------------------------------

Have any suggest?!

**Comment by yukiarimo** [comment]
Of course, it doesn't! It will be fixed in the new release in a few days. You have to use CUDA. MPS is macOS only.

**Comment by yukiarimo** [comment]
Fixed!
