### ISSUE TITLE
Model training and fine tuning

### ISSUE THREAD

**Issue by yukiarimo** [yukiarimo/yuna-ai#2]

**Comment by yukiarimo** [comment]
So far support for .bin LoRA adapters is here. No fine-tuning yet! Check llamacpp for more details.

**Comment by cloner174** [comment]
where are the .bins ???

**Comment by yukiarimo** [comment]
> where are the .bins ???

Currently, we don't have our own bins or gguf for LoRA or the Model. Please utilize the Pygmalion model available here: https://huggingface.co/TheBloke/Pygmalion-2-7B-GGUF/blob/main/pygmalion-2-7b.Q5_K_M.gguf

Why?
1) I'm currently focused on improving functionality, not the mode itself.
2) We are still in the process of collecting datasets, and I lack a powerful NVIDIA setup to expedite this.

If you’re interested in discussing the project, have some brilliant ideas or wanna help me with it, please DM me on discord: (yukiarimo)[https://discord.com/users/1131657390752800899]

**Comment by yukiarimo** [comment]
If anyone has ideas for a training mechanism (cause interference logic was changed in v5.2), leave a comment here!
