### ISSUE TITLE
No module named 'whisper'

### ISSUE THREAD

**Issue by niardordenravt** [yukiarimo/yuna-ai#28]
C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "A:\Project\AI\cust GPT\yuna-ai\index.py", line 6, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'

I'm not really a scriptor or into scripting stuff,but wanna try ur project and found this error message,what I should do? thank you

**Comment by yukiarimo** [comment]
1. Install the dependencies: check out the `index.sh` file
2. Soon, there will be a significant upgrade, but it's not a real issue
3. For more information, search for `yukiarimo` on Discord or visit my website [www.yukiarimo.com](http://www.yukiarimo.com/) and DM me.

**Comment by yukiarimo** [comment]
I can't replicate this bug, so I'm closing the issue.

**Comment by biship** [comment]
whisper isn't in requirements.txt

**Comment by yukiarimo** [comment]
I see.

**Comment by yukiarimo** [comment]
Tomorrow will be a new release into the `main` beach. So keep updated!

**Comment by biship** [comment]
Also, it needs to be openai-whisper, not whisper

**Comment by yukiarimo** [comment]
Will be updated in a week.
