### ISSUE TITLE
Regarding yuna model instalation

### ISSUE THREAD

**Issue by niardordenravt** [yukiarimo/yuna-ai#38]
So when I try to install Yuna model,it stated

 fatal: repository 'https://huggingface.co/TheBloke/Pygmalion-2-7B-GGUF/resolve/main/pygmalion-2-7b.Q5_K_M.gguf/' not found

when I open index.sh I found out that

install_yuna_model() {
    echo "Installing Yuna model..."
    git clone https://huggingface.co/TheBloke/Pygmalion-2-7B-GGUF/resolve/main/pygmalion-2-7b.Q5_K_M.gguf lib/models/yuna/
}

is it right? or it should be  
git clone https://huggingface.co/yukiarimo/yuna-ai

?

**Comment by niardordenravt** [comment]
after git clone,still don't know where to find these file...

//yuna-ai-2-7b-role-play.ggufyuna-ai-2-7b-role-play.gguf

**Comment by yukiarimo** [comment]
Hello, the development team here! It sounds terrible. We recently got some issues, so not everything could work! If you’re interested in more details and further information, please don't hesitate to get in touch with me on the discord: `yukiarimo#4577`.

**Comment by yukiarimo** [comment]
Got updated the main branch a little bit. It’s in the beta, but you can try. The stable version with everything working will be in the end of this week

**Comment by niardordenravt** [comment]
thanks for the replies. Well since I'm not into some coding stuff which I don't know anything, like...at all since I'm just a mere 3D artist,what I can do is just trying and reporting.
Cool stuff u create there,good luck man

**Comment by yukiarimo** [comment]
Oh, okay, thanks anyway! We’re just trying to speed up the development (cause it has been a while) to make some demos soon! By the way, if you want, you can help us make a 3D/2D model of Yuna :)!

**Comment by yukiarimo** [comment]
Huuu! Got updated! Check out the latest stable version, v6.1! If you have more questions, please feel free to reopen this!
