### ISSUE TITLE
Please make sure to include "CUDA is Required" in the readme.

### ISSUE THREAD

**Issue by ymsboob** [yukiarimo/yuna-ai#53]
**Is your feature request related to a problem? Please describe.**
I put a few hours into installation without knowing CUDA was required, my system doesn't have a GPU, just a 12th gen i7 so I thought I could handle it, after a few hours of struggle, I got this message and it genuinely upset me: `CUDA error 100 at /home/runner/work/ctransformers/ctransformers/models/ggml/ggml-cuda.cu:5067: no CUDA-capable device is detected`

**Describe the solution you'd like**
Please specify CUDA being required in the readme with big letters.

**Comment by yukiarimo** [comment]
I understand your situation. I apologize for any inconvenience caused by the installation process. If you don't have a GPU, you can use the CPU version of the transformers. However, I use MacOS, so I cannot test whether it works on other devices besides MPS!

**Comment by yukiarimo** [comment]
> `CUDA error 100 at /home/runner/work/ctransformers/ctransformers/models/ggml/ggml-cuda.cu:5067: no CUDA-capable device is detected`

By the way, on which step did you get this message?

**Comment by ymsboob** [comment]
> > `CUDA error 100 at /home/runner/work/ctransformers/ctransformers/models/ggml/ggml-cuda.cu:5067: no CUDA-capable device is detected`
> 
> By the way, on which step did you get this message?

After installing everything and running the `python index.py` so technically the first step in the index.sh

I haven't found any way of using transformers without CUDA, can you elaborate further?

**Comment by 0xGingi** [comment]
@ymsboob

in your config.json, change device to CPU and set gpu layers to 0

**Comment by yukiarimo** [comment]
Wait a minute, we’re already working on the solution. If you don’t mind, can you please DM me on Discord (search for `yukiarimo#4577`)?

**Comment by 0xGingi** [comment]
I made a pull request that will use CPU by default
