### ISSUE TITLE
JSON parse error since no convo file

### ISSUE THREAD

**Issue by gitmanbloggus** [yukiarimo/yuna-ai#70]
**Describe the bug**
every response is a JSON prase error since there isn't a convo log file auto created, which means it tries to add to a invisible logs and thus I don't get a response from yuna

**To Reproduce**
Start Yuna and try typing something in

**Expected behavior**
get a response from the model

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Endeavor OS, aarch64
 - Browser firefox
 - Version latest

**Smartphone (please complete the following information):**
 since it runs locally on the rpi4 it can't be tested on my phone

**Additional context**

**Comment by yukiarimo** [comment]
Yes, I know.

1. You're probably trying the main branch
2. Please wait a few days; I will merge an update soon!

**Comment by gitmanbloggus** [comment]
it fixed itself
