### ISSUE TITLE
Not using 4 cores/threads when configured

### ISSUE THREAD

**Issue by gitmanbloggus** [yukiarimo/yuna-ai#80]
**Describe the bug**
Yuna isnt using 4 cores when i setted it to use 4 cores

**To Reproduce**
1. Go to settings
2. set threads to something higher then 2
3. Send message
4. Check core usage using something that sees individual core usage
**Expected behavior**
it's supposed to use n cores and not cap at 2

**Screenshots**
![Screenshot 2024-03-26 17-53-12.png](https://github.com/yukiarimo/yuna-ai/assets/130293623/6634e973-a502-4007-8dfc-3d3e4de4d296)

**Desktop (please complete the following information):**
 - OS: [Raspian 12 (apt changed to trixie)]
 - Browser [Chromium]
 - Version [122]

**Smartphone (please complete the following information):**
 Ironically:
 not working for me (typed ip in completely & corrected in both Firefox + Chrome and nothing happened)

**Additional context**
nothing

**Comment by yukiarimo** [comment]
@gitmanbloggus What are your parameters for `config.json`?
