### ISSUE TITLE
(CondaPython) PS D:\Git\yuna-ai-6.3> Python .\index.py wont start

### ISSUE THREAD

**Issue by Kolouch-Dominik** [yukiarimo/yuna-ai#83]
**Describe the bug**

Traceback (most recent call last):
  File "D:\Git\yuna-ai-6.3\index.py", line 178, in <module>
    app.run(host='0.0.0.0', port=4848, ssl_context=('cert.pem', 'key.pem'))
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\flask\app.py", line 610, in run
    cli.show_server_banner(self.debug, self.name)
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\flask\cli.py", line 758, in show_server_banner
    click.echo(f" * Serving Flask app '{app_import_path}'")
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\click\utils.py", line 318, in echo
    file.write(out)  # type: ignore
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\click\_compat.py", line 542, in _safe_write
    return _write(s)
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\click\_winconsole.py", line 192, in write
    return self._text_stream.write(x)
  File "C:\Users\Dominik\miniconda3\envs\CondaPython\lib\site-packages\click\_winconsole.py", line 177, in write
    raise OSError(self._get_error_message(GetLastError()))
OSError: Windows error 6
**Expected behavior**

 - OS: win11
 - Browser opera,google
 - Version yuna-ai-6.3

**Comment by yukiarimo** [comment]
Please generate SSL certificates. You can use this command: `openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365`

**Comment by Kolouch-Dominik** [comment]
> Please generate SSL certificates. You can use this command: `openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365`

There is nothing about ssl in the installation requirements.
Anyway, I get an error message when I run the command.
(CondaPython) PS D:\yuna-ai-6.3> openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365
Can't open "C:\Program Files\Common Files\ssl/openssl.cnf" for reading, No such file or directory
942E0000:error:80000003:system library:BIO_new_file:No such process:crypto\bio\bss_file.c:67:calling fopen(C:\Program Files\Common Files\ssl/openssl.cnf, r)
942E0000:error:10000080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:75:

**Comment by yukiarimo** [comment]
Please download OpenSSL from the official website, and then you should try again or use the generated certificates in the project.

**Comment by Kolouch-Dominik** [comment]
I was able to start the server using the visual studio debugger, but just like the website (https://www.yuna-ai.live/yuna.html) there is an error in the chat
https://ctrlv.cz/kFkr
https://ctrlv.cz/ZQb4

**Comment by yukiarimo** [comment]
1. Certificates were uploaded in the last release to both the `main` and the `dev` branches:
https://github.com/yukiarimo/yuna-ai/blob/main/key.pem
https://github.com/yukiarimo/yuna-ai/blob/main/cert.pem
2. I have no idea why this error happened, but there could be a few reasons:
2.1. The `OpenSSL` tool should installed on your machine (you can find an installation manual online). Here's a download link: https://www.openssl.org/source/
2.2. Maybe you can't use my certificates and should have your own, so please try the first step
3. About your initial `Win 6` error, you can check this solution: https://stackoverflow.com/questions/63325149/running-exe-without-a-console-oserror-winerror-6-the-handle-is-invalid (never heard of it before)
4. Additional stuff could help: https://stackoverflow.com/questions/7360602/openssl-and-error-in-reading-openssl-conf-file

**Comment by yukiarimo** [comment]
The website https://www.yuna-ai.live/ serves as a landing page for now. Therefore, you shouldn't use it as a live demo (of AI), mainly because it's not even connected to any server!

We're already resolving this. But because of the `GitHub Pages` requirement, I wasn't able to link it to the running server + the server is not always live (VPS)

**Comment by Kolouch-Dominik** [comment]
Thank you for your help.

**Comment by yukiarimo** [comment]
I don't know if this is related, but you could try using Python 3.8 instead. It seems to fix a lot of issues in any project!

**Comment by yukiarimo** [comment]
> It works with the cert and key in this repo tho, no need to create it myself

Thanks, good to know!

> Lib>site-packages>flask and opened app.py I commented the

Do you want to say that's a Flask's problem?

**Comment by yukiarimo** [comment]
> But I'm stuck with default settings. I can't change her profile and such

You can modify the config.json for the model run and the "kanojo" on the profile page (don't forget to click save; it should work). Yes, the new release is coming this week with MORE customization specifically for ya ;)

> After a restart of Yuna-AI, a chat history was created, and Yuna-AI works without any issues

Often, you just need to reload the page to fetch new data and write configs. I can't make it automatically because it causes infinite loops and errors. If you're talking about the server, this is probably again your Flask issue :(
