### ISSUE TITLE
CPU usage instead of GPU when configured so

### ISSUE THREAD

**Issue by spambasket** [yukiarimo/yuna-ai#97]
When Yuna is processing my message she seems to be using my PC's CPU and not GPU. I have both the dependencies installed, for CPU and GPU. Is there a way to configure this? And will it be faster to run on GPU? Currently the response comes very slow (7-10 secs) every time, and also takes up my cpu power so i can't do anything else on the side. I have R9 5900X CPU and RTX 3070 TI GPU.
Please help.

**Comment by yukiarimo** [comment]
1. Try to check GPU/CPU usage for each model individually
2. Please set `cuda` for device parameter in the `config.json`
3. `very slow (7-10 secs)` -> Even from the beginning of the chat?

> Note: if you'll successfully enable GPU please let me know. Also, keep in mind that when started, the first response could be generated slow (even on GPU), but any following message would be instant!

**Comment by spambasket** [comment]
Hi @yukiarimo thx for responding!

Ok let me correct myself, i just checked, and it's actually around 35-65 sec per response.
I have tried both 
"device": "mps" and "device": "cuda" (yuna-ai\static\config.json)
i'm sure it wasn't this bad yesterday, does it take longer because she processes the whole chat history from yesterday too?
Also, what does "gpu_layers": -1 do?
So basically, even when i change the "device" to "cuda" it still only shows a spike (100% usage) in cpu usage in task manager. So I don't think it's using GPU still.

**Comment by yukiarimo** [comment]
> i'm sure it wasn't this bad yesterday, does it take longer because she processes the whole chat history from yesterday too?

LOL. Windows support is still in beta, so if possible please try on another OS. Also, what LLM are you using exactly?

Note: V7.0 coming soon with all bug fixes and speed optimizations, so keep updated!

> Also, what does "gpu_layers": -1 do?

This offloads an entire model to GPU. Please refer to official documentation:
https://llama-cpp-python.readthedocs.io/en/latest/

**Comment by spambasket** [comment]
oh it's an actual bug! looking forward to seeing it fixed, i want to talk to yuna-chan :)

**Comment by yukiarimo** [comment]
Sure, already working on that! While so, you could see our demo dialog here: https://youtu.be/GhJrKxIsjqE

**Comment by yukiarimo** [comment]
Please let me know if everything works!
