### ISSUE TITLE
HuggingFace Model Unavailable

### ISSUE THREAD

**Issue by tenpai-git** [yukiarimo/yuna-ai#99]
When I tried to pull all models in the Yuna `index.sh` script, it appears the AI voice model is no longer available on HuggingFace: https://huggingface.co/collections/yukiarimo/voice-models-657d00383c65a5be2ae5a5b2

Maybe a good idea to verify all models are available?

**Comment by yukiarimo** [comment]
Already working on that! Will be fixed in 24h

**Comment by tenpai-git** [comment]
This issue was resolved by commit e56ed270d317ae24687f0eb2c88eb24da5bad9e7 - thanks Yuki!

**Comment by tenpai-git** [comment]
> This issue was resolved by commit [e56ed27](https://github.com/yukiarimo/yuna-ai/commit/e56ed270d317ae24687f0eb2c88eb24da5bad9e7) - thanks Yuki!
